
services:
  - type: web
    name: myapp-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    python:
      version: 3.9.13
    envVars:
      - key: DATABASE_URL
        value: postgresql://user:password@host:port/dbname
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    plan: free
    healthCheckPath: /health
